name: 'Project Recognition'
description: 'Recognizes affected area based on changed files'
inputs:
  projects:
    description: 'Projects to be recognized. JSON string'
    required: false
  token:
    description: 'GitHub token'
    required: true
outputs:
  matrix:
    description: 'Matrix based on label entities in JSON format'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: eye
  color: gray-dark
